const SUPPIERS_LIST = [
  "Bhoomi Visa and Travel Services",
  "The Institute of Indian Foundrymen-TN",
  "Earth Metallurgical Services Private Limited",
  "H D M Power Corporation",
  "Interglobe Aviation Limited (TN)",
  "M/S. Dharsan Enterprises",
  "Ryan Associates",
  "SNV Aviation Private Limited-KA",
  "SNV Aviation Private Limited-MH",
  "Interglobe Aviation Limited-G",
  "Interglobe Aviation Limited-AP",
  "Interglobe Aviation Limited-KA",
  "Craftech Packaging",
  "Karnataka Polymer Product",
  "Leghorngroup Private Limited",
  "SYNERGY-GLOBAL MANUFACTEC PRIVATE LIMITED",
  "Jana Plumbing Co Ltd",
  "D.M.HARDWARE and Tools",
  "Inspirenest Solutions Private Limited",
  "Gyanendra Srivastava",
  "Mahaveer Transport",
  "Marine Freight Lines India Private Limited",
  "Claresta",
  "M.R.RAJHSHEKAR & Co",
  "Texsilk Outdoor Fabrics",
  "Sakthi Industry",
  "Pragson Manufacturing Technology",
  "Clasic Art",
  "Sri Ganesh Industries",
  "Sundry Creditors FI",
  "Colombus Freight Logistics Private Limited",
  "Mechtek Laboratory LLP",
  "Khedut Hardware & Paints",
  "Precision Sintered Products",
  "Chandra CFS and Terminal Operators Private Limited",
  "Vedant Multi Specialty Hospital",
  "Sachin Shims Private Limited",
  "Sujan Impex Private Limited",
  "Giftana India Private Limited",
  "United Forge Industries",
  "J T Enterprises",
  "Tuv Sud South Asia Private Limited",
  "MRV Enterprises",
  "Bajrang Bronze LLP",
  "Bright Inspection Services",
  "Royal Aqua Plus",
  "Rahil air bubbles pvt. ltd.",
  "Dhanalakshmi Metal Finishers",
  "SSK Transpoprt",
  "Bindal Agencies Private Limited",
  "Life Insurance Corporation of India",
  "Alisha Enterprises",
  "Pramukh hardware",
  "Accurate India Instruments",
  "Reliance Retail Limited",
  "S v Medicals",
  "Rohan Fire Safety Equipments",
  "Saraswathi Electricals",
  "U.B.CHEMI Technologies",
  "Quality Rubber and Engineering Enterprises",
  "Kartavya Enterprise",
  "Bhingare castings private limited",
  "Shree bhagvati ceterers",
  "Sri kumaran precisions",
  "Goutham Handicrafts",
  "Hema Metal Works",
  "CHIRU TRANSPORT",
  "Pavan industries",
  "Asteroid Metal",
  "R. Vijendran",
  "Ambibuzz Technologies LLP",
  "Dhwani Enterprise (Amazon)",
  "City Organisers Pvt Limited",
  "Amtech Technocast Private Limited",
  "WWL Transport Solutions (India) Pvt Ltd",
  "Shree Balaji Handlooms",
  "Fei Cargo Limited",
  "Ups Express Private Limited-Karnataka",
  "Shivansh digital",
  "Sunil Forging and Steel Industries (Unit-II)",
  "Chair choice",
  "Info Strapping Systems",
  "Maestro engineers",
  "Markone Systems & Services",
  "Zedek Safety Products Private Limited",
  "Diya Infotech",
  "Western interio furniture private limited",
  "Sr Engineering Works",
  "Bright Burnishing Tools Private Ltd.",
  "Tarpaulin Solutions",
  "Quad Tooling Technologies",
  "Packings & Jointings Gaskets Private Limited",
  "Dxso Soft",
  "SPAENAUR FASTENERS RIGHT NOW",
  "Customised Technologies Private Limited",
  "Aashish Tours & Travels",
  "Creative Meta Plast Products Private Limited",
  "Eagle Fleet Services Private Limited",
  "BRITTEL PRO PRIVATE LIMITED",
  "Intelligent Sourcing Services Ltd",
  "Diesel (India) Nitride Private Limited",
  "Laghu Udyog Bharati",
  "HDFC Bank Sundry Cr.(I),Karnataka",
  "Marvel techno industries",
  "Banu Tools",
  "Mani Srinivasan & Associates",
  "Sri Azhaguthai Transports",
  "Lubrall industries pvt ltd",
  "AMC PLAST TECH INDUSTRIES",
  "V.J.INDUSTRIES",
  "Mahalakshmi Metal Corporation",
  "SHREE RAMDEV TRADERS",
  "Orion Coupling",
  "AATMAN AIR SOLUTION",
  "A K PIPE FITTINGS PVT LTD",
  "National Electric Coil dba Hesgon",
  "Roots Corporation Limited",
  "Galaxy Exhibition Systems LLP",
  "Royal Sundaram General Insurance Co. Limited",
  "Clicktech Retail Private Limited",
  "Level and Flow Control Engineers",
  "NIRAJ PROCESSORS",
  "Ramdev Roofing",
  "Poornimaa Paper & Stationery",
  "Ganesh Papers",
  "Paatm Shiva (Amazon)",
  "Oddpod India (Amazon)",
  "Rajendra Paper Agencies(New)",
  "Anchor Fluid Power",
  "Ganvi Enterprises",
  "Moorthi Instruments Private Limited",
  "CENTRAL ROADWAYS Warehouse & Storage",
  "S & T Engineering",
  "The Construction Company",
  "Associated Road Carriers Limited",
  "S M S TRANSPORT",
  "AMTEC TECHNOLOGIES",
  "Ups SCS (India) Private Limited",
  "Kapsun Packaging",
  "Sri Ganga Enterprises",
  "Ups Express Private Limited",
  "S.S.STEELS",
  "Sridharan L",
  "Keka Technologies Private Limited",
  "Srinivasa Gardening",
  "MARUTHI FAB TECH",
  "IMAGE SYNERGY EKXPLOR PRIVATE LIMITED",
  "Technoking Enterprise",
  "Indian Institute of Materials Management",
  "Qc Square",
  "Bharat Trading Company",
  "Royal Plastic",
  "Aps Industries",
  "Akarshak graphics",
  "Dodiya Prafula Sureshbhai",
  "Interglobe Aviation Limited - MH",
  "Unit Electric Ltd.",
  "Synergy Global Sourcing (H)",
  "Sudarshan book distributors",
  "HDFC Ergo General Insurance Company Limited",
  "International Customs Services,Inc",
  "Monel Forge & Fittings",
  "Eepc India M",
  "S K Catering",
  "Nettigritty Private Limited",
  "Peri Industrial Services Private Limited",
  "Quality Circle Forum of India",
  "Inno Metallurgical Services Private Limited",
  "Ma Durga Electricals & Hardware",
  "Royal Ceramics",
  "Agarwal Sweets - Erode",
  "DHL EXPRESS (INDIA) PRIVATE LIMITED",
  "SRI GANGA PARAMESHWARI TRADERS",
  "Crystal Cargo",
  "Tamil Nadu Transport",
  "Futuretech Industrial Services",
  "Micro Metal Engineers",
  "Sanjay R Patel (Rent Payable)",
  "Nitin R Patel- Rent",
  "Geographical Indications Tagged World Premium Products Private Limited",
  "ECGC Ltd Salem-SCR Policy 0220001337",
  "ECGC LITD Salem-SBE Policy 0220002116",
  "UMAMAHESHWARI TEMPO SERVICE",
  "Dev Crane Service",
  "Aruna Oil Castings",
  "ROYAL HARDWARES & TOOLS",
  "Synergy Global Brands",
  "Asp Information Technologies",
  "Shree Karan Metal Technologies",
  "Phinix Metrology Lab LLP",
  "Public Transport Service",
  "International Software Consultants LLP",
  "German Calibration Lab LLP",
  "TRANSGLOBAL LOGISTICS, TN",
  "Ragass",
  "SRP Facilities Services",
  "N N Industries",
  "Armstrong International Consultants",
  "Hosur Industries Association",
  "Multitech Metal Impregnations",
  "Kaveri Industrial Gases",
  "Sri Krish Automation",
  "Paras Tools and Technologies",
  "VPS Manpower Solutions",
  "SIVARANJANI HOTEL",
  "DELHIVERY LIMITED",
  "L A S ENTERPRISES",
  "Jam Ranjit Carriers",
  "Central Roadways",
  "Viraat Industries",
  "Sree Vasavi Logistics",
  "Bharti Roadways",
  "S K LOGISTICS",
  "FedEx Express Transportation and Supply chain Service, Maharashtra",
  "UPS Express Private Gujarat",
  "HINDON ENGINEERING WORKS",
  "RM Engineering",
  "BITMAP INFOMATIC",
  "M/S SHAKTHI TOOLS",
  "Tuba Engineers",
  "TRIUMPH ENGINEERING TECHNOLOGIES",
  "Reliance Jio Infocomm Limited",
  "Building Contract",
  "Sm Packing Solutions",
  "Aum Surface Technology, KA",
  "Best Taxi",
  "Nishta Legal",
  "Gagana Design Studio",
  "GANESAN TRANSPORT",
  "Nilesh Vasani ( Mobile App)",
  "J. Srinivasan",
  "Usha A Kumar",
  "Conceptia Software Technologies Pvt Ltd",
  "Surface Innovation",
  "Hema's Enterprises Private Limited",
  "Sri Vishnu Heat Treatment",
  "Seenu Transport Pvt Ltd - TN",
  "Patel Wooden Industries",
  "Nature Transport",
  "Nagaraj Tours and Travels",
  "Madhavaa Crafts Private Limited",
  "Jio Platforms Limited",
  "Venkateshwara Industries",
  "Distinct Productivity Solutions Private Ltd TN",
  "Central Roadways",
  "Bit Technocrafts",
  "Mars Technologies",
  "Sri Hema Industries",
  "Skymech Automation & Controls",
  "Upskill Academy",
  "The Evergrand Palace",
  "SMS LINERS",
  "3D Product Development Private Limited",
  "TCI Express limited-Gujarat",
  "Shree Varun Wooden Industries",
  "PrafulKumar Masribhai Gorfad",
  "Monarch Appliances Pvt Ltd",
  "Smart Shift Logistics Solutions Private Ltd",
  "Sachiya Steel International Private Limited",
  "Protek Fastners",
  "Fabulous Designs And Creations",
  "Bharat Sanchar Nigam Limited",
  "ICICI Lombard General Insurance Company Limited",
  "Yitong Global Logistics and Marketing Pvt Ltd",
  "V-Trans (India) Ltd, Gujarat",
  "The Institute of Indian Foundrymen-WB",
  "Shree Milk Supply",
  "Safexpress Private Limited",
  "Matrix Inspection & Engineering Services Pvt. Ltd",
  "IndTax Consultants",
  "Inac Brass Pvt. Ltd",
  "Guru Fastners",
  "Gford Institute Of Management Private Limited",
  "Franklincovey Training And Consulting L L P",
  "Evergreen NDT Engineers",
  "Central Institute Of Petrochemicals Engineering & Technology",
  "Carl Zeiss India (Bangalore) Private Limited",
  "Bharat Heavy Electricals Limited",
  "Aganita Ventures Private Limited",
  "Abk Aots Dosokai Tamilnadu Centre",
  "Unit Electric Ltd",
  "NS TOOLS",
  "Dominion Metallurgical, Inc",
  "DeZURIK,Inc.",
  "Unit Electrical Engineering Ltd",
  "PRAGATHI LOGISTICS SERIVICES PRIVATE LIMITED-TAMIL NADU",
  "PRAGATHI LOGISTICS SERVICES PRIVATE LIMITED-KARNATAKA",
  "TULASI ELECTRICALS & LIGHTING PALACE",
  "SMB METAL AND STEEL SYNDICATE",
  "BHANDARI INDUSTRIAL ENTERPRISES",
  "Narayanan R",
  "Usha A Kumar",
  "GRT JEWELLERS (INDIA) PRIVATE LIMITED",
  "LUCKY RESIDENCY",
  "S.R.S. TRAVELS / S.R.S. LOGISTICS",
  "LAXMI KRUPA ABRASIVESS (P) LTD",
  "SUMANGALI HARDWARE",
  "PARCEL BY NIGHT PRIVATE LIMITED",
  "Mainfreight India Private Limited",
  "Ben Line Agencies (India) Private Ltd- Maharashtra",
  "BEN LINE AGENCIES (INDIA) PRIVATE LIMITED-TAMIL NADU",
  "Karmek Engineering Services",
  "IND-TAX CONSULTANTS",
  "SR Computer",
  "Cast Strategies LLC",
  "Indian Machine Tool Manufacturers Association- Karnataka",
  "Indian Machine Tool Manufacturers Association-Maharashtra",
  "Indian Machine Tool Manufacturers Association-Haryana",
  "Indian Machine Tool Manufacturers Association-Tamil Nadu",
  "Bontech Computer And Services",
  "Bharti Airtel Limited",
  "WCO Consultants Private Limited",
  "Blue Moon Logistics Pvt Ltd - Uttar Pradesh",
  "Blue Moon Logistics Pvt Ltd- Maharashtra",
  "Pooja Agencies",
  "Rajendra Paper Agencies",
  "FEDEX Express Transportation And Supply Chain Services (I) Pvt Ltd- Bengaluru",
  "FEDEX EXPRESS TRANSPORTATION AND SUPPLY CHAIN SERVICES (I) PRIVATE LIMITED - MAHARASHTRA",
  "FEDEX EXPRESS TRANSPORTATION AND SUPPLY CHAIN SERVICES (I) PRIVATE LIMITED- GUJARAT",
  "FEDEX Express Trasnportation And Supply Chain Services (I) Pvt Ltd- Tamilnadu",
  "SCIENTIFIC PEST CONTROL SERVICES",
  "Anchappa Chetty- Hosur Guest House",
  "Thennarasu Painting Contractor",
  "Sri Venkateshwara Minerals",
  "Sri Achudha Associates",
  "RRR Security Services",
  "Prakash Traders",
  "Murugan Printers",
  "J A A & CO LLP",
  "Feminity Health Products",
  "Favourite Engineering",
  "Elcoats & Allied Industries",
  "VRL Logistics Limited- Gujarat",
  "Jay Enterprises",
  "Standard Spring And Metal Pressing Works",
  "TCI Freight (A Division Of Transport Corp. Of India Limited)",
  "OnCall HR & IT Services",
  "Bharat Sanchar Nigam Limited",
  "VRL Logistics Limited- Tamilnadu",
  "Navnit Engineering Works",
  "Simplex Enterprises",
  "Maruthi Enterprises",
  "V Kumar and Co",
  "M R Vekatesh",
  "GIFTDORO INDIA LLP",
  "RKC Containers Private Limited",
  "NAVEEN INDUSTRIAL CORPORATION",
  "Santhosh Lifestyle",
  "Supreme Packages",
  "C C Awards",
  "Pilotferro Cast Private Limited",
  "ICICI Bank Limited - MH",
  "HDFC Bank Sundry Cr.(I),Mumbai",
  "ICICI Bank Limited (Sundry Creditors) L",
  "HDFC Bank Limited 'CR' (L)",
  "Triangle innovations Pvt Ltd",
  "Shyam Products",
  "Tescom",
  "G.R.STEELS",
  "Jay Jalaram Precision Component LLP",
  "Metalic Technoforge Limited",
  "Wonder Valley Recreations and Hospitality Private Limited",
  "VRL Logistics Ltd, Punjab",
  "VRL Logistics Ltd, Maharashtra",
  "VRL Logistics Ltd, Karnataka",
  "VRL Logistics Ltd, Haryana",
  "Vergin Technologies",
  "Varam Super Speciality Hospital & Fertility Centre",
  "Transcell Systems",
  "THINKROI Private Limited",
  "Tespa Calibration Services",
  "TCI Express Limited-TN",
  "Sri Venkateshwara Hydralics",
  "Sri Safe Thaksha Enterprises",
  "Shree Venkateshwara Fuel and Service Station",
  "Shree Venkatesh Engineering Works LLP",
  "QR Filing",
  "Prakash Fabrication",
  "Poly Fluoro Limited",
  "PHEONIX 3D Metrology and Design Solutions",
  "Pandian Stores",
  "Om International Courier & Cargo",
  "N T Muzammil Ahmed Khan and Associates",
  "McKinley & Rice Creativity Private Limited",
  "Makemytrip (India) Private Limited",
  "Katiyan Consulting Services Private Limited",
  "Info Edge (India) Limited",
  "Imperial Corporate Services",
  "HIMA ALUMINIUM HEAT TREATERS",
  "Friends Track",
  "Freight Express International Private Limited",
  "Evo Supply Chain Private Limited",
  "EEPC India-WB",
  "Dhona & Co",
  "Cimtrix Systems (P) Ltd.",
  "Cedrus Silicone Private Limited",
  "Bharti Roadways",
  "Baker Gauges India Private Limited",
  "Ark Weighing Solution",
  "Agarwal Bhavan Sweets-Hosur",
  "Sri Vedha Technologies",
  "Santhya Preapplieds",
  "RKR Security Services",
  "Fine Trading & Service",
  "Sd Hosur Casting",
  "Express Ventures Private Limited",
  "Kuehne Nagel Private Limited- TN",
  "Kuehne Nagel Private Limited-Maharashtra",
  "Calimere Technologies",
  "Sitas-Ndt Engineers Private Limited",
  "VISTHAR LLC",
  "Home Designers & Fabricators (P) Ltd (Hotel Hills)",
  "Ningbo Deco Imp. & Exp. Co Ltd",
  "Airfiber Networks Private Limited",
  "KK Industries",
  "ECGC LTD",
  "TATA AIG General Insurance Company Limited",
  "J.T. Enterprises",
  "Avinash Cargo Pvt Ltd",
  "Laksha Enterprises",
  "MicroLab Testing Private Ltd",
  "Mashalla Transport",
  "Diamond Ndt Inspection Services (P) Ltd",
  "DSV Air and Sea Private Limited, TN",
  "DSV Air and Sea Private Limited,MH",
  "DSV Air and Sea Private Limited, KA",
  "Tiger Security Services",
  "Wework India Management Pvt Ltd",
  "Jitentanti",
  "SSS Transport",
  "TUV Rheinland India Pvt Ltd",
  "TUV India Private Ltd",
  "Trans Global Logistics (C)",
  "Trans Global Logistics (B)",
  "Trans Global Logistcs (M)",
  "World Wide Logistics India Pvt Ltd(M)",
  "Worldwide Logistics (India) Pvt Ltd. (G)",
  "Worldwide Logistics India Pvt Ltd (C)",
  "World Wide Logistics (India) Pvt. Ltd (B)",
  "Gati Express & Supply Chain Private Ltd,TN",
  "Gati Express & Supply Chain Private Ltd, Gujarat",
  "Professional Pest Control Service",
  "Seenu Transport Pvt Ltd-Bangalore",
  "Precise Testing and Calibration Centre Pvt Ltd",
  "Sree Vasavi Transport",
  "Sri Sai Ram Catering",
  "Canal Enterprise",
  "POWERCON SYSTEMS & MARKETING",
  "Ningbo Bestop Industrial Co Ltd",
  "Aura Precision Private Limited",
  "Amwin Machining Private Limited",
  "Anjana Enterprises",
  "Arthi Designing and Machining Works",
  "Arihant Ispat",
  "K.K Industries",
  "Digitalveli Technologies",
  "Tbot Techno Systems Pvt Ltd",
  "Bendy Products Limited",
  "Sri Balaji Associates",
  "Ashok Industries(uniquest composite)",
  "Bharadia Engg. Ltd",
  "Harsha Engg Pvt Ltd",
  "Kaizen Hi Tech Pvt Ltd",
  "Plast Tech Engineering",
  "Rajamane Industries Pvt Ltd",
  "Rajhans Alloys Pvt. Ltd.,",
  "Senor Metals Pvt. Ltd.",
  "Satyam cartoons",
  "Sthallform Technik Pvt. Ltd.,",
  "Accu Precisions",
  "Achieve Techno Cast Private Ltd",
  "Om Water jet Machining Pvt. Ltd.,",
  "Annai Industries",
  "Casting India",
  "Sahney KirkWood Pvt Ltd",
  "Delta CNC Applications",
  "Thayyil Fab",
  "Rapsri Engineering Products Comp",
  "Micro Tech CNC",
  "Fitco Orings Pvt Ltd",
  "Topsun Industries",
  "Yajamana Automation Technologies",
  "Highspeed Appliances",
  "ATC Technologies",
  "Rajamane & Hegde Services Pvt.Ltd.",
  "AUM Surface Technology",
  "ENGINEERED POLYMERS (I) P LTD,",
  "Aerospace Engineered",
  "Arul Polymers Pvt Ltd",
  "Magcore Lamination",
  "Rising Metal & Alloys",
  "Santhamani Engineering",
  "Prefect Hydraulics",
  "Estee Auto Pressing",
  "Bhandari Precision",
  "Vertex Fittings",
  "Uma Springs Private Limited",
  "Bagadia Chaitra",
  "Dot A Technologies",
  "Shubham Steel Industries",
  "Sunikh Components Pvt Ltd",
  "KPSV Industries Pvt Ltd",
  "Synergy global MFG",
  "Bunny Industries",
  "Hex Cable Accessories Pvt.Ltd",
  "ANR Colour Coaters",
  "SV Rubber Industries Pvt Ltd",
  "AUM Creation",
  "New Cast Die Casting",
  "Macho Engineering Industries",
  "Aruna Pressure Die Casting",
  "Auto Packaging Supply &service",
  "Sri coat",
  "Micro Precision Tooling",
  "Steel Engineering Enterprises",
  "Spectro Ductile Iron Pvt.Ltd",
  "Chandan Foundry & Industrial Corporation",
  "Excel Die Casters Pvt Ltd",
  "Apollo Technoforge Pvt Ltd",
  "SEP INDIA PVT LTD",
  "Hydrolines India",
  "Aerotech Enginnering Technologies",
  "Micro Supreme Auto Industries (I) Pvt Ltd",
  "East India Technologies Private Limited",
  "Sankalp Technologies",
  "Neueco Packsolutions PVT.LTD",
  "CastFab Engineering India PVT LTD",
  "Altech Alloys India Pvt. Ltd",
  "Wintech",
  "Shraddha product",
  "Sterling brass industries",
  "Adroit International",
  "Premier Engineering works",
  "Ravi Plast mold Pvt ltd",
  "Arcturus castings",
  "MVD fastners private limited",
  "Sree Lakshmi Electromech",
  "Synergy punching Pvt ltd.",
  "Rapid precision engineering",
  "Saify Ind Unit - II",
  "Polyhose india private Ltd",
  "Sealtite Dichtungs Pvt Ltd",
  "Capital Engineering",
  "P.C sons Casting Pvt Ltd.",
  "Jay Jalaram Precision Components LLP",
  "Balu auto components pvt Ltd",
  "Origincadd infotech",
  "Nimbus Industries",
  "Sterling Technocast LLP",
  "Kobolt casting pvt ltd",
  "Fluid pumps and equipment india pvt ltd",
  "Ethernal alloy cast pvt ltd.",
  "United Enterprises",
  "Jagdish Technocast Pvt Ltd",
  "Classic Polymers & Resins",
  "Jagathshree castings",
  "Malkar industries",
  "Leak Proof Cast India Private Ltd",
  "Yantransh Gas spring LLP",
  "Maxwell AutoComponents Pvt Ltd",
  "Vasanthi Foundry",
  "Shivalaya Precision Components Pvt Ltd",
  "Autocoats",
  "Essae Gears And Transmissions Private Limited",
  "Distinct productivity solutions",
  "Perfect Metacraft LLP",
  "Amtech Technocast",
  "Microform Automation",
  "Raman Thermosets Pvt Ltd",
  "Hydrobenz Industries Private Limited",
  "Audhe industries",
  "Igus (India) Pvt. Ltd",
  "High Tech Sintered Products Pvt Ltd",
  "Hoshi Tools Private Limited",
  "Innocoat System",
  "Chethan Industries",
  "Vista Powder Coating",
  "MECHMET ENGINEERS",
  "Madras Hydraulic Hose (P) Ltd",
  "Unique Tooling Solutions Pvt Ltd",
  "Creatal Foundries",
  "KMC Glass and Aluminium Pvt Ltd",
  "Ace Tooling Solutions",
  "Vinod Technologies",
  "Aerospace and Special Processes",
  "Castlegate Industrial Holdings Pvt Ltd",
  "I Will Paper Products",
  "Teksell Industries",
  "SATTVA ALLOYS",
  "Dart Engineering and Technology",
  "Siddhi Cast Pvt Ltd",
  "BHARAT BALANCING WEIGHTS & CO",
  "Inspen Technology Pvt Ltd",
  "Dietech India Private Limited",
  "Pooja Western Metaliks Limited",
  "Pelican Bathware Private Limited",
  "Crystal Engineering Systems Private Limited",
  "AB Carter India Pvt Ltd",
  "GK Industrial Components LLP",
  "SUNRISE ELECTROPLATERS",
  "Alzest Auto Cast",
  "Shelltec Engg.Ancilaries India Pvt Ltd",
  "Pitti Industries P Ltd",
  "Tritonvalves Climatech Private Limited",
  "Newall Engineering Works",
  "Pragati Engineering Belgaum Pvt Ltd",
  "Timken GGB Technology P Ltd",
  "UUMT Engineering and Industrial Systems",
  "Accurate Steel Forgings (India) LTD",
  "Anita Steels",
  "Ashtavinayaka Overseas",
  "B.V Enterpeises",
  "Bhandari steels",
  "Cavier Bath Fittings Ltd",
  "Choudary Steel Syndicate",
  "INAC Brass",
  "Indo German Tools",
  "PEM",
  "International Springs and Stampings Private Limited",
  "Jainsons Industries",
  "Size Master Gauges",
  "Krishna Saw Mill & Wood Works",
  "Metacast (NEW)",
  "Mo Finnish",
  "Multi Tech",
  "Paras Industries",
  "Patel Brass Turnomatics Pvt. Ltd.",
  "Patel Metal",
  "Pressed Products",
  "Ravi Products",
  "Shiv Extrusion",
  "Branopac India Pvt Ltd",
  "Shree Raj Steels",
  "Spraymet",
  "SS Engineering",
  "Steel Corporation",
  "Sun Laser Cutting",
  "Times Enterprises",
  "Paras Industries",
  "Venus Industries",
  "Vinpla Plating Pvt Ltd",
  "Metal Mesh",
  "Turn tech cnc",
  "Spaniq CNC",
  "Ripple Technology",
  "Marvel Works",
  "Anisaa Enterprises",
  "Dipti Metals",
  "Shree Laxmi industries",
  "Sigma Punch",
  "S.V.R Industries",
  "Sri venkateswara engineeering",
  "YK Technologies",
  "Kapsun Forming",
  "Rohit Agencies",
  "Raghu Industries",
  "Sudarsan technologies",
  "Lisy Industries",
  "Kanti Engineering",
  "Sunglow industries",
  "Bhavaana Industries",
  "Samarth Gauges & Tools",
  "SS Filters Pvt Ltd",
  "Creative Technologies",
  "CS Power System",
  "KS Enterprises",
  "SSS Engineerings",
  "Moorthi Instruments",
  "SLN Surface Finishers",
  "Precision CNC Eng",
  "Balaji Press Tech",
  "SRI Lavanya Springs Pvt Ltd",
  "Bir Valve Industries",
  "Dattaguru Industries P Ltd",
  "SRL Engineering",
  "Shiva Ferric Pvt Ltd",
  "Shree Rajeshwari Engineering",
  "KRS industries",
  "Prosim R&D Pvt Ltd",
  "Atul Fasteners",
  "Technocrat Engineering Services",
  "Ken 2V Engineers Pvt Ltd",
  "Kavin Tech Engineering",
  "Macro Precision",
  "Sneha Springs Industries",
  "Sri Raghavendra Meterial Testing Services",
  "CVR",
  "Chetan Gears",
  "Klassic Tools & Accessories",
  "Benson",
  "Bath Touch Metal Pvt. Ltd.",
  "Sree Venkateshwara Industries",
  "Star Engineering Patterns",
  "Swastik Packaging industries",
  "Sonia Enterprises",
  "Akaash Intrument & Gaauges India",
  "Arjay Alloys Pvt Ltd",
  "LGG Tools",
  "MNS Machine Tools",
  "V.J Industries",
  "Abhi Auto Products",
  "Accuratte Engineering",
  "Southern Steel Industries",
  "Kamakshi Plastic Components",
  "HiTech Dynamic",
  "Sundha Fastners",
  "Sunrise Metal Cast",
  "Vinit Performance Polymers Pvt Ltd",
  "SRIS FASTENERS PRIVATE LIMITED",
  "G.S International",
  "Mit Cast Alloy",
  "Sri Renuka Industries",
  "Foreaxis Technology(New)",
  "Sri Shiva Technical Service",
  "High Precision Technologies",
  "TRIDENT TECHNOLOGIES",
  "Hindustan Automation",
  "Innox Precision (I) PVT LTD",
  "Cris Engineering Works",
  "Rohitech Auto Industries",
  "Systems Alloys",
  "Prema Engineering",
  "MJM Fine Enclosures Pvt LTD",
  "Adroit Die Castings",
  "QUALITY THERMOPACK AND INSULATIONS INDUSTRIES",
  "Bhoruka Fabcons Pvt Ltd",
  "SRV Metal Finishers",
  "Sree Ganesh Engineering",
  "Dhanalakshmi",
  "North Lab",
  "TNEB",
  "Tranglobal Logistics",
  "Thirupathi Courier",
  "Gaia Plants",
  "Vijendran",
  "S Vasudevan",
  "Global Systems",
  "OJUS Power and Technologies Private Limited",
  "JEM Technologies",
  "P.Mani",
  "TUV SUD south Asia",
  "Star Health insurance",
  "ECGC",
  "EEPC",
  "Nibe power solution",
  "Cholamandalam Ms General Insurance Company Limited.",
  "Airtel",
  "Victory powder Coating",
  "Asian Springs",
  "Super Engi Tech pvt Ltd.",
  "AN engineer",
  "R.B casting",
  "Shubhlaxmi metals and tubes Pvt Ltd.",
  "D.S.Engineering Services",
  "Nicam industries",
  "Akar Industry",
  "Techtra automation",
  "Hind metal & allied Inds.",
  "Hardik industries",
  "Sri bharath industries",
  "V TECH",
  "K P ENGINEERING",
  "Crest Metal Engineering LLP",
  "Sri Munishwarar Electro plating",
  "Concept Colour Tecniks Pvt. Ltd",
  "Arma plast",
  "Sri Gowrish CNC Private Limited",
  "RK Automation",
  "Techno Matrix",
  "Mahendra Tech",
  "Futura Kitchen Sinks India Pvt Ltd",
  "Feedtec Industry",
  "Marksz automation",
  "Sri Balaji Engineering",
  "SV Engineering",
  "Global Casting",
  "Fabulous designs & creations",
  "Pragathi Precision",
  "Vin Dip India Pvt Ltd",
  "Armour Technocast",
  "Subajeyam Turners",
  "Efiltek Private Limited",
  "Standard Spring & Metal Pressing Works",
  "NRAJ PROCESSORS",
  "Intex Tools and Components Pvt Ltd",
  "SYSTA MET INDIA PRIVATE LIMITED",
  "JT CORP",
  "Maruti Techno industries",
  "Lee Spring Company India Pvt Ltd",
  "R R Industries",
  "Spareage Sealing Solutions LLP",
  "Shree Sai Glass",
  "Mighty Machines",
  "Globe-Tech Fortune Industries Pvt Ltd",
  "Multi Tech Laser Engineering India Pvt Ltd",
  "Suraj Metal Corporation",
  "Innoforge P Ltd",
  "Ability Engineering P Ltd",
  "Masha Allah",
  "T.Saifuddin & Co",
  "Maheswari Plastics",
  "Max Serve Industries Pvt Ltd",
  "Carbochem Products Private Limited",
  "Roovel Solutions Pvt Ltd",
  "Manoj Electricals",
  "Akshara Instruments",
  "Paras Tools and Equipment",
  "A K Technologies",
  "Sumangali Hardware",
  "A K Associates",
  "Green Cartons",
  "J.K. Industries",
  "Next Packaging Machinery Pvt Ltd",
  "Sri Vigneshwara Enterprises",
  "MAAP INSTRUMENTATION",
  "Crescent Technobuild Pvt Ltd",
  "Sri Maha Vishnu Enterprises",
  "JPHN Industries",
  "Techpark Power Solutions",
  "New Feet Fashions",
  "TEQ Serve IT Solutions",
  "KIMA Furniture",
  "Shiva Hardwares",
  "REMY PACKAGING",
  "Skm Enterprises",
  "Fine Finish Industries Pvt Ltd",
  "Image Labels Private Ltd",
  "Storage Technologies and Automation Ltd",
  "Keka Technologies Pvt Ltd",
  "Akshayaa Multi Cleaning System Pvt Ltd",
  "K. H. Packaging Solutions",
  "R B Infotech",
  "Standard Furnitures",
  "Sri Geetha Textiles",
  "R.G.S. Enterprises",
  "Afza Material Handling and Storage Systems",
  "Merc Technologies",
  "Shreya Beverages",
  "Himmel Machine Tools Pvt Ltd",
  "Kiran Hardware & Electricals",
  "Unique Measurement Service",
  "Sri Bala Enterprises",
  "Krishna Packers",
  "Manufactec Solutions India Pvt Ltd",
  "SACHIYA STEEL INTERNATIONAL",
  "RS Components & Controls (I) Ltd.",
  "Varna Coats Private Limited",
  "Parasmani Chemicals",
  "Sri Sai Sakthi Engineering",
  "Pap-Tech Engineers and Associates",
  "Supreme Packs Plastic Private Limited",
  "The Computer Consultant",
  "Synergy Global Sourcing(R)",
  "YANTRANSH VALVES PRIVATE LIMITED",
  "Ganesh Super Shoppe",
  "Hardhika Engineering Works",
  "Bismi Trading Company",
  "S&S INDUSTRAIL ENTERPRISES",
  "Ningbo Gastac Gas Spring Co.,Ltd.",
  "Trupthi Enterprises",
  "Vinod Plastic House",
  "SUPER HOBS & BROACHES PRIVATE LIMITED",
  "Kalpana Sharma",
  "MOKO TECHNOLOGY LTD",
  "Weightonics Automation Systems",
  "Matrix NDT Inspection Services India Private Limited",
  "Hesgon Narrow Fabrics",
  "Vardhmaan Automation",
  "Lakshmi Fasteners",
  "SHIVAM POLY PRODUCTS",
  "Adithyaa Industrial Products",
  "Size Control Gauges and Tools Pvt Ltd",
  "Inetest Technologies India Pvt.Ltd.",
  "Technocraft Automation",
  "LAXMI KRUPA ABRASIVESS PVT LTD",
  "The Oriental Rubber Trading Co(Mysore) Pvt Ltd",
  "PMC CORPORATION",
  "PUMA LIFT TRUCKS PVT LTD",
  "M/s.Shanghai T & S Eva Brass and Bronze Works Co. Ltd",
  "V N Associates",
  "Bits Technologies",
  "N.N. Industries",
  "Sree Velan Two Wheelers LLP",
  "RVR Surface Finishers",
  "Esquire Multiplast Private Limited",
  "Bontech Computer And Services",
  "Siri Motor Ventures Private Limited",
  "Hitech International",
  "Madura Furniture",
  "Sri Saravanaa Fabs",
  "Maharashtra Jewellery Tools",
  "Diamond Carbide India Pvt Ltd",
  "SVB Bearings Private Limited",
  "Uniquest Composites Private Limited",
  "Sri Mahalakshmi Woods",
  "Stolt India Private Limited",
  "Golden Furniture",
  "BBW Global Tek Private Ltd",
  "VIP Steel Centre LLP",
  "Harihar Vision Solutions",
  "First Leaf Fashion",
  "Ningbo Yinzhou Jasan Trading Co. Ltd",
  "Unique Steel Products",
  "A K TECHNOLOGIES",
  "Sai Shanmuga Enterprises",
  "Crafter Engineering Hub",
  "Blue Bell Enterprises",
  "Aadi Electronics",
  "Cris Trade Mart",
  "Sri Raghvendra Enterprises",
  "Design Wings",
  "Jaisun Industrial Solutions",
  "star engineering",
  "Surface Shot Finishers",
  "Perfect Graphics",
  "Jeeva Process",
  "Classik Plastic Innovations LLP",
  "Hi-Tech Chairs and Furniture",
  "Varuns Innovations",
  "METAL SALES (INDIA)",
  "Sri Vinayka Enterprises",
  "Venture Network Enterprises",
  "Rajdeep Associates",
  "Ace Trading Co",
  "MNR Enterprises",
  "Kavitha Industries",
  "Zawar Gauges & Tools Pvt Ltd",
  "Simplex Enterprises",
  "Tri-Wall Pak Private Limited",
  "Hira Holovision",
  "Kalai Tooling System",
  "Sri Bala Murugan Metal Works",
  "Sharada Electro Chem",
  "PR Technocast"
];
